### PR TITLE
makeflex

### PR DESCRIPTION
**Pull request by RMeli**
### Description

This PR provides a few fixes for the `makeflex.py` script:

* Fix issue with non-standard H names starting with a number (`1HD1`, ...)
* Print original atom name for the atoms in flexible residues
* Fix issue with indices: if flexible residues contain hydrogen atoms, subsequent atoms are misplaced (or missing)

### Fix Issue with Non-Standard H

The script uses `` to skip H atoms. Some H atom names start with numbers (see `LEU 52` in system `10gs` of PDBbind18), therefore the following is more robust:
```
atype = line[76:].strip()
if atype != "H":
```

### Print Original Atom Name

The original atom name `aname = line[12:16].strip()` is printed in the final PDB instead of the atom type `atom.getName()`. This makes the comparison easier.

### Fix Issue with Indices

Using `makeflex.py` on system `10gs` of PDBbind18 made a carbon atom disappear from `TRP 38`. Looking deeper into the issue, I realized that when H atoms are present in the flexible residues, the increment
```
which[(chain, resnum)] += 1  # update to next index
```
leads to a misalignment (since `if atype != "H"`, such increment is skipped). Excluding H when selecting the atoms in flexible residues seems to solve the problem.

This behavior can be seen with `ARG 13` in system `10gs` of PDBbind18. The result of lexible docking is the following:
```
ATOM     21  C   ARG A  13      16.152   2.121  24.667  1.00  0.00           C  
ATOM     22  C   ARG A  13      17.452   1.819  25.406  1.00  0.00           C  
ATOM     23  C   ARG A  13      15.815   3.611  24.771  1.00  0.00           C  
ATOM     24  C   ARG A  13      15.134   4.161  23.528  1.00  0.00           C  
ATOM     25  C   ARG A  13      14.508   5.512  23.799  1.00  0.00           C  
ATOM     26  N   ARG A  13      15.491   6.499  24.239  1.00  0.00           N  
ATOM     27  H   ARG A  13      16.373   6.584  23.695  1.00  0.00           H  
ATOM     28  C   ARG A  13      15.331   7.295  25.293  1.00  0.00           C  
ATOM     29  N   ARG A  13      14.229   7.219  26.031  1.00  0.00           N  
ATOM     30  H   ARG A  13      13.485   6.534  25.787  1.00  0.00           H  
ATOM     31  H   ARG A  13      14.110   7.845  26.853  1.00  0.00           H  
ATOM     32  N   ARG A  13      16.280   8.162  25.612  1.00  0.00           N  
ATOM     33  H   ARG A  13      17.147   8.219  25.040  1.00  0.00           H  
ATOM     34  H   ARG A  13      16.159   8.786  26.435  1.00  0.00           H
``` 
and the result of `makeflex.py` before the fix is the following (without backbone atoms):
```
ATOM    186  CA  ARG A  13      16.152   2.121  24.667  1.00  0.00           C
ATOM    188  C   ARG A  13      17.452   1.819  25.406  1.00  0.00           C
ATOM    190  CB  ARG A  13      15.815   3.611  24.771  1.00  0.00           C
ATOM    193  CG  ARG A  13      15.134   4.161  23.528  1.00  0.00           C
ATOM    196  CD  ARG A  13      14.508   5.512  23.799  1.00  0.00           C
ATOM    199  NE  ARG A  13      15.491   6.499  24.239  1.00  0.00           N
ATOM    201  CZ  ARG A  13      16.373   6.584  23.695  1.00  0.00           C
ATOM    202  NH1 ARG A  13      15.331   7.295  25.293  1.00  0.00           N
ATOM    205  NH2 ARG A  13      14.229   7.219  26.031  1.00  0.00           N
```
We see that the carbon atom 201 has the same coordinates of the hydrogen atom 27. With the fix, the result is the following (without backbone atoms):
```
ATOM    186  CA  ARG A  13      16.152   2.121  24.667  1.00  0.00           C
ATOM    188  C   ARG A  13      17.452   1.819  25.406  1.00  0.00           C
ATOM    190  CB  ARG A  13      15.815   3.611  24.771  1.00  0.00           C
ATOM    193  CG  ARG A  13      15.134   4.161  23.528  1.00  0.00           C
ATOM    196  CD  ARG A  13      14.508   5.512  23.799  1.00  0.00           C
ATOM    199  NE  ARG A  13      15.491   6.499  24.239  1.00  0.00           N
ATOM    201  CZ  ARG A  13      15.331   7.295  25.293  1.00  0.00           C
ATOM    202  NH1 ARG A  13      14.229   7.219  26.031  1.00  0.00           N
ATOM    205  NH2 ARG A  13      16.280   8.162  25.612  1.00  0.00           N
```
where carbon 201 has now the correct coordinates of carbon atom 28. The same goes for other atoms after the first H atom.

## PR

I'm doing more tests, therefore I suggest not to merge this PR just yet.

### CODE REVIEW

**Comment by RMeli** [comment]
The alignment fix seems to fix also visualization problems with VMD, where chain A for `10gs` was not correctly visualized with `NewCartoon`; not the two structures are perfectly superimposed.

**Comment by RMeli** [comment]
A few more [tests](https://github.com/RMeli/gsoc19/tree/master/datasets/flexdock/test) provide the expected results (checked manually using VMD).

**Comment by dkoes** [comment]
I assumed the additional tests meant it was ready for merging.  Can you add a couple lines to the README on how to use?

**Comment by RMeli** [comment]
Yes, I'll perform more tests later on with a larger sample but everything looks good to me at the moment.

I'll add some lines to the README, but I'll have to test it on a PDB file with multiple models first (I used `obabel` to split the results of docking in different poses, before using `makeflex.py`).

**Pull request merged**
