### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by francoep**
I added 3 more usage sections.

### CODE REVIEW

**Review by dkoes — COMMENTED** [review]
enemble?

**Comment by francoep** [comment]
I didn't want to add another section for that, and it is explained in the options at the end, which I tried to point to with the statement in the parens

**Comment by dkoes** [comment]
enemble is not a word.

**Comment by francoep** [comment]
ohhhhhhhh, I just committed the fix for the spelling error.

**Review by dkoes — APPROVED** [review]

**Review by dkoes — APPROVED** [review]

**Pull request merged**
